# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Azure DevOps
# CI pipeline for PSRule-vscode

variables:
  version: '1.0.0'

 # Use build number format, i.e. 1.0.0-B2105001
name: $(version)-B$(date:yyMM)$(rev:rrr)

trigger:
  branches:
    include:
    - 'main'
    - 'release/*'
  tags:
    include:
    - 'v1.*'

pr:
  branches:
    include:
    - 'main'
    - 'release/*'

stages:

# Build pipeline
- stage: Build
  displayName: Build
  dependsOn: []
  jobs:

  - template: jobs/build-channel.yaml
    parameters:
      channel: preview

  - template: jobs/build-channel.yaml
    parameters:
      channel: stable

# Test pipeline
- stage: Test
  dependsOn: [ 'Build' ]
  jobs:

  - template: jobs/test.yaml
    parameters:
      name: macOS_10_15
      displayName: 'PowerShell 7.1 - macOS-10.15'
      imageName: 'macOS-10.15'
      channel: preview

  - template: jobs/test.yaml
    parameters:
      name: windows
      displayName: 'PowerShell 5.1 - win2016'
      imageName: 'vs2017-win2016'
      channel: preview

  - template: jobs/test.yaml
    parameters:
      name: windows_2019
      displayName: 'PowerShell 7.1 - Windows 2019'
      imageName: 'windows-2019'
      channel: preview

  - template: jobs/testContainer.yaml
    parameters:
      name: ps_7_1_ubuntu_20_04
      displayName: 'PowerShell 7.1 - ubuntu-20.04'
      imageName: mcr.microsoft.com/powershell
      imageTag: 7.1.3-ubuntu-20.04
      channel: preview

# Analysis pipeline
- stage: Analysis
  displayName: Analysis
  dependsOn: []
  variables:
    # Already done in build
    skipComponentGovernanceDetection: true
  jobs:
  - job: Secret_Scan
    pool: 'Hosted VS2017'
    displayName: Secret scan
    steps:
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
      displayName: 'Scan for secrets'
      inputs:
        debugMode: false
        toolMajorVersion: V2

    - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
      displayName: 'Publish scan logs'
      continueOnError: true

    - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
      displayName: 'Check for failures'
      inputs:
        CredScan: true
        ToolLogsNotFoundAction: Error

# Release pipeline
- stage: Preview
  displayName: Preview
  dependsOn: [ 'Build', 'Analysis' ]
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v1.')
  jobs:
  - template: jobs/publish-channel.yaml
    parameters:
      channel: preview

# Release pipeline
- stage: Stable
  displayName: Stable
  dependsOn: [ 'Build', 'Analysis' ]
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v1.')
  jobs:
  - template: jobs/publish-channel.yaml
    parameters:
      channel: stable
    
  - job: update_github_release
    displayName: Update GitHub release
    pool:
      vmImage: 'ubuntu-20.04'
    steps:

    # Update GitHub release
    - task: GitHubRelease@0
      displayName: 'GitHub release'
      inputs:
        gitHubConnection: 'AzureDevOps-PSRule-vscode'
        repositoryName: '$(Build.Repository.Name)'
        action: edit
        tag: '$(Build.SourceBranchName)'
        releaseNotesSource: input
        releaseNotes: 'See [change log](https://github.com/Microsoft/PSRule-vscode/blob/main/CHANGELOG.md)'
        assetUploadMode: replace
        addChangeLog: false
        isPreRelease: false
